### ISSUE TITLE
Sudoku does not take box_size as an argument

### ISSUE THREAD

**Issue by Leo-Lifeblood** [messersm/sudokutools#3]
!pip install sudokutools

from sudokutools.sudoku import Sudoku
Sudoku(box_size=(3, 3))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-ee9c2010e182>](https://localhost:8080/#) in <cell line: 2>()
      1 from sudokutools.sudoku import Sudoku
----> 2 Sudoku(box_size=(3, 3))

TypeError: Sudoku.__init__() got an unexpected keyword argument 'box_size'

**Comment by messersm** [comment]
Use `Sudoku(size=(3, 3))`.

Details: Please check your version of sudokutools. Pypi serves `0.4.0` which is documented [here](https://sudokutools.readthedocs.io/en/0.4.0/index.html). If you want to use a newer commit you'll have to install directly from github.
